import{a as d,i as n,S as q}from"./assets/vendor-64b55ca9.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))l(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&l(i)}).observe(document,{childList:!0,subtree:!0});function s(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function l(e){if(e.ep)return;e.ep=!0;const o=s(e);fetch(e.href,o)}})();async function y(t,r){d.defaults.baseURL="https://pixabay.com";const s=await d.get("/api/",{params:{key:"42191077-576543231991193ea17287b56",q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:b}});if(s.status!==200)throw new Error("Failed to fetch images");return s.data.hits.length===0&&n.error({message:"Sorry, there are no images matching your search query. Please try again!",messageSize:10.5,position:"topRight"}),s.data.hits}function h(t){const r=t.map(({webformatURL:l,largeImageURL:e,tags:o,likes:i,views:L,comments:w,downloads:S})=>`<li class="gallery-item">
              <a class="gallery-link" href="${e}">
                <img
                  class="gallery-image"
                  src="${l}"
                  alt="${o}"
                />
              </a>
              <div class="image-details">
                <p><b>Likes</b> ${i}</p>
                <p><b>Views</b> ${L}</p>
                <p><b>Comments</b> ${w}</p>
                <p><b>Downloads</b> ${S}</p>
              </div>
           </li>`).join("");f.insertAdjacentHTML("beforeend",r),new q(".gallery a",{captionsData:"alt"}).refresh(),m.style.display=t.length>0?"block":"none"}const c={searchForm:document.querySelector(".search-form"),input:document.querySelector('[type="text"]')},f=document.querySelector(".gallery"),p=document.querySelector(".loader"),u=document.querySelector(".loader.moreLoader");console.log(u);const m=document.querySelector(".loadBtn");let a=1,g="";const b=15,v=Math.ceil(100/b);c.searchForm.addEventListener("submit",I);m.addEventListener("click",P);async function I(t){t.preventDefault();const r=c.input.value.trim();if(!r){n.error({message:"Fill in the input field!",position:"topRight"});return}p.style.display="block",g=r,a=1;try{const s=await y(g,a);R(s)}catch{n.error({message:"An error occurred while fetching images!",position:"topRight"})}finally{p.style.display="none"}c.searchForm.reset()}async function P(){u.style.display="block",a++;try{const t=await y(g,a);if(h(t),console.log(t),a===v)return m.style.display="none",n.error({position:"topRight",message:"We're sorry, there are no more posts to load"});const r=$();window.scrollBy({top:r*2,behavior:"smooth"})}catch(t){console.log(t),n.error({message:"An error occurred while fetching more images!",position:"topRight"})}finally{u.style.display="none"}}function R(t){f.innerHTML="",h(t)}function $(){return document.querySelector(".gallery-item").getBoundingClientRect().height}
//# sourceMappingURL=commonHelpers.js.map
